version: 2
updates:
  # Main project npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      development:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Documentation site npm dependencies
  - package-ecosystem: "npm"
    directory: "/docs-src"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    groups:
      documentation:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 2