name: Benchmark

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Run performance benchmarks
        run: npm run bench:perf

      - name: Run bundle size analysis
        run: npm run bench:size

      - name: Generate benchmark report
        run: npm run bench:all

      - name: Upload benchmark results
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: benchmarks/BENCHMARK_RESULTS.md

      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const results = fs.readFileSync('benchmarks/BENCHMARK_RESULTS.md', 'utf8');

            // Extract key metrics from the report
            const bundleWins = results.match(/nano-string-utils has the smallest bundle size in (\d+) out of (\d+)/);
            const summary = bundleWins 
              ? `📊 **Benchmark Results**: nano-string-utils wins ${bundleWins[1]} out of ${bundleWins[2]} functions for bundle size`
              : '📊 Benchmark results generated';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${summary}\n\n<details>\n<summary>View full benchmark report</summary>\n\n${results}\n\n</details>`
            });

      - name: Store benchmark results for comparison
        if: github.ref == 'refs/heads/main'
        uses: actions/cache@v4
        with:
          path: benchmarks/BENCHMARK_RESULTS.md
          key: benchmark-results-${{ github.sha }}
          restore-keys: |
            benchmark-results-
